
CREATE SEQUENCE S_ENZH INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1;
GRANT SELECT,UPDATE ON SEQUENCE S_ENZH TO GROUP "Users";
GRANT ALL ON SEQUENCE S_ENZH TO GROUP "Admins";

CREATE TABLE T_ENZH
(
	F_SID		int8	NOT NULL DEFAULT nextval('S_ENZH'),
	F_Source		VARCHAR(1024),
	F_Target		VARCHAR(1024),
	F_Domain		CHAR(2) DEFAULT '00',
	F_Owner		int4 DEFAULT 0,
	F_Permit		int4 DEFAULT 0,
	F_From		int4 DEFAULT 0,
	PRIMARY KEY (F_SID)
);
CREATE INDEX ENZH_Domain_Index ON T_ENZH (F_Domain);
CREATE INDEX ENZH_Permit_Index ON T_ENZH (F_Permit);
GRANT SELECT,INSERT,DELETE ON TABLE T_ENZH TO GROUP "Users";
GRANT ALL ON TABLE T_ENZH TO GROUP "Admins";

CREATE TABLE T_ENZH_ENX
(
	F_Word		VARCHAR(64)	NOT NULL,
	F_SID		int8	NOT NULL,
	F_Offset		int2 DEFAULT 0,
	PRIMARY KEY (F_Word,F_SID),
	FOREIGN KEY (F_SID) REFERENCES T_ENZH (F_SID) ON DELETE CASCADE
);
GRANT SELECT,INSERT,DELETE ON TABLE T_ENZH_ENX TO GROUP "Users";
GRANT ALL ON TABLE T_ENZH_ENX TO GROUP "Admins";

CREATE TABLE T_ENZH_ZHX
(
	F_Word		VARCHAR(64)	NOT NULL,
	F_SID		int8	NOT NULL,
	F_Offset		int2 DEFAULT 0,
	PRIMARY KEY (F_Word,F_SID),
	FOREIGN KEY (F_SID) REFERENCES T_ENZH (F_SID) ON DELETE CASCADE
);
GRANT SELECT,INSERT,DELETE ON TABLE T_ENZH_ZHX TO GROUP "Users";
GRANT ALL ON TABLE T_ENZH_ZHX TO GROUP "Admins";
