<!--<table width="700"><tr><td align="center">
<img src="/transmem/images/footer.jpg" border="0"><br>
<font size="-1">Copyright 2007, Transmem</font>
</td></tr></table>-->
<div class="ehFooter">
	<ul>
		<li><a href=""><%=rb.getString("home.aboutus")%></a></li>
		<li>|</li>
		<li><a href=""><%=rb.getString("home.features")%></a></li>
		<li>|</li>
		<li><a href=""><%=rb.getString("home.stories")%></a></li>
		<li>|</li>
		<li><a href=""><%=rb.getString("home.help")%></a></li>
		<li>|</li>
		<li><a href=""><%=rb.getString("home.jobs")%></a></li>
		<li>|</li>
		<li><a href=""><%=rb.getString("home.tus")%></a></li>
		<li> | </li>
		<li><a href=""><%=rb.getString("home.tellfriend")%></a></li>
		<li> | </li>
		<li><a href=""><%=rb.getString("home.privacy")%></a></li>
		<li> | </li>
		<li><a href="" onclick="return register()"><%=rb.getString("home.register")%></a></li>
	</ul>
	<br /><br />
	<div id="left"><H5>&copy; 2006-2008 <a href="" class="copyright">transmemo.com</a>&nbsp;&nbsp;
	<a href="terms.htm" class="copyright"><%=rb.getString("home.terms")%></a><br /><%=rb.getString("home.summary")%></H5>
	</div>
</div>
