<!-- personal info page tabs -->
<p>
<div id="tabs_s">
<ul id="tabs">
<li id="tab_1"><a href="" onclick="return turn2page('personal1.jsp')"><%=rb.getString("smenu_personal_info")%></a></li>
<li id="tab_2"><a href="" onclick="return turn2page('personal2.jsp')"><%=rb.getString("smenu_personal_edit")%></a></li>
<li id="tab_3"><a href="" onclick="return turn2page('personal3.jsp')"><%=rb.getString("smenu_personal_stat")%></a></li>
<li id="tab_4"><a href="" onclick="return turn2page('personal4.jsp')"><%=rb.getString("smenu_personal_buy")%></a></li>
</ul>
</div>
</p><br>
